#!/usr/bin/env node

/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/

/*
  This is a command-line utility to monitor and print out APRS packets from a
  TCP KISS device, like an instance of the DireWolf sound card modem.
*/
var path=require('path');
var util=require('util');
var ax25utils=require('utils-for-aprs').ax25utils;
var WebSocketAprsDataEndpoint=require('utils-for-aprs').WebSocketAprsDataEndpoint;
console.log("process.argv=" + process.argv);

if (process.argv.length != 3) {
  console.log("Usage: node %s <ws-url>", path.basename(process.argv[1]));
  return;
}

var url=process.argv[2];
/*
  The pipeline is sort of like this:
    Endpoint -> Console
*/

//Create the endpoint
var endpoint=new WebSocketAprsDataEndpoint(url);

// When we get data on the endpoint, show it on the console.
endpoint.on('aprsData', function(frame) {
  frame.receivedAt=new Date();

  console.log( "[" + frame.receivedAt + "]" + ax25utils.addressToString(frame.source) +
    '->' + ax25utils.addressToString(frame.destination) +
    ' (' + ax25utils.repeaterPathToString(frame.repeaterPath) + ')' +
    frame.info);
});
endpoint.on('error', function(err, frame) {
  console.log("Got error event:" + err);
  console.log("Frame is:" + JSON.stringify(frame));
});

// Log interesting events...
endpoint.on('connect', function(connection) {
  console.log("Connected to " + endpoint.url);
  connection.on('disconnect', function() {
    console.log('Lost connection');
  });
});

// Turn on the endpoint.  It will attempt to connect in a persistent fashion.
endpoint.enable();
