#!/usr/bin/env node

/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/

/*
  This is a command-line utility to monitor and print out APRS packets from a
  TCP KISS device, like an instance of the DireWolf sound card modem.
*/
var path=require('path');
var util=require('util');
var ServerSocketKISSFrameEndpoint=
  require('utils-for-aprs').ServerSocketKISSFrameEndpoint;
var APRSProcessor=require('utils-for-aprs').APRSProcessor;

console.log("process.argv=" + process.argv);

if (process.argv.length != 3) {
  console.log("Usage: node %s <port>", path.basename(process.argv[1]));
  return;
}

/*
  The pipeline is sort of like this:
    Endpoint -> APRSProcessor -> Console
*/

//Create the endpoint
var endpoint=new ServerSocketKISSFrameEndpoint();
endpoint.host="localhost";
endpoint.port=process.argv[2];
var aprsProcessor=new APRSProcessor();

// When we get data on the aprsProcessor, show it on the console.
aprsProcessor.on('aprsData', function(frame) {
  console.log(frame);
});
aprsProcessor.on('error', function(err) {
  console.log("Got eror event:" + err);
});

// The endpoint provides de-escaped KISS frames.  Pass them on to the aprsProcessor


// Log interesting events...
endpoint.on('connect', function(connection) {
  console.log("Connected to port " + endpoint.port);
  connection.on('data', function(frame) {
    aprsProcessor.data(frame);
  });
  connection.on('disconnect', function() {
    console.log('Lost connection');
  });
});



// Turn on the endpoint.  It will attempt to connect in a persistent fashion.
endpoint.enable();
